### ISSUE TITLE
mysql batch insert contains uuid binary(16) field not support

### ISSUE THREAD

**Issue by heckledai** [1448376744/SqlBatis#1]
database: mysql
SqlBatis.DbQuery<T>.ResovleBatchInsert need detemine byte[] and insert like 0x1234

**Comment by 1448376744** [comment]
yes ado.net It does not support batch adding. I use the insert batch script. I suggest you read the source code first, inherit dbcontext and re implement it

**Comment by heckledai** [comment]
private string ResovleBatchInsert(IEnumerable<T> entitys)
        {
            var table = GetTableMetaInfo().TableName;
            var filters = new GroupExpressionResovle(_filterExpression).Resovle().Split(',');
            var columns = GetColumnMetaInfos()
                .Where(a => !a.IsComplexType).ToList();
            var intcolumns = columns
                .Where(a => !filters.Contains(a.ColumnName) && !a.IsNotMapped && !a.IsIdentity)
                .ToList();
            var columnNames = string.Join(",", intcolumns.Select(s => s.ColumnName));
            if (_context.DbContextType == DbContextType.Mysql)
            {
                var buffer = new StringBuilder();
                buffer.Append($"INSERT INTO {table}({columnNames}) VALUES ");
                var serializer = GlobalSettings.EntityMapperProvider.GetDeserializer(typeof(T));
                var list = entitys.ToList();
                for (var i = 0; i < list.Count; i++)
                {
                    var item = list[i];
                    var values = serializer(item);
                    buffer.Append("(");
                    for (var j = 0; j < intcolumns.Count; j++)
                    {
                        var column = intcolumns[j];
                        var value = values[column.CsharpName];
                        if (value == null)
                        {
                            buffer.Append(column.IsDefault ? "DEFAULT" : "NULL");
                        }
                        else if (column.CsharpType == typeof(bool) || column.CsharpType == typeof(bool?))
                        {
                            buffer.Append(Convert.ToBoolean(value) == true ? 1 : 0);
                        }
                        else if (column.CsharpType == typeof(DateTime) || column.CsharpType == typeof(DateTime?))
                        {
                            buffer.Append($"'{value}'");
                        }
                        else if (column.CsharpType == typeof(byte[])) {
                            string hexstr = string.Empty;
                            for (int index = 0; index < ((byte[])value).Length; index++) {
                                hexstr += Convert.ToString(((byte[])value)[index], 16).PadLeft(2, '0');
                            }
                            buffer.Append($"0x{hexstr}");
                        }
                        else if (column.CsharpType.IsValueType || (Nullable.GetUnderlyingType(column.CsharpType)?.IsValueType == true))
                        {
                            buffer.Append(value);
                        }
                        else
                        {
                            var str = SqlEncoding(value.ToString());
                            buffer.Append($"'{str}'");
                        }
                        if (j + 1 < intcolumns.Count)
                        {
                            buffer.Append(",");
                        }
                    }
                    buffer.Append(")");
                    if (i + 1 < list.Count)
                    {
                        buffer.Append(",");
                    }
                }
                return buffer.Remove(buffer.Length - 1, 0).ToString();
            }
            throw new NotImplementedException();
        }

**Comment by heckledai** [comment]
i repaire byte[] batch insert,please add code to git hub master

**Comment by heckledai** [comment]
in ResovleBatchInsert function add this detemine code:
                    else if (column.CsharpType == typeof(byte[])) {
                        string hexstr = string.Empty;
                        for (int index = 0; index < ((byte[])value).Length; index++) {
                            hexstr += Convert.ToString(((byte[])value)[index], 16).PadLeft(2, '0');
                        }
                        buffer.Append($"0x{hexstr}");
                    }

**Comment by 1448376744** [comment]
ok

> 在 ResovleBatchInsert 函数中添加此 detemine 代码：
> 否则 if （列.CsharpType = 类型类型 （字节）） =
> 字符串十六进制 = 字符串。空;
> 用于 （int 索引 = 0; 索引 < （（字节+） 值）。长度;索引 =）
> = 十六进制 = 转换.Tostring（（（字节=）值）=索引=，16）。垫左（2，'0'）;
> •
> 缓冲区。附录（$"0x[十六进制]）;"0x=十六进制";
> }



> 在 ResovleBatchInsert 函数中添加此 detemine 代码：
> 否则 if （列.CsharpType = 类型类型 （字节）） =
> 字符串十六进制 = 字符串。空;
> 用于 （int 索引 = 0; 索引 < （（字节+） 值）。长度;索引 =）
> = 十六进制 = 转换.Tostring（（（字节=）值）=索引=，16）。垫左（2，'0'）;
> •
> 缓冲区。附录（$"0x[十六进制]）;"0x=十六进制";
> }

ok

**Comment by 1448376744** [comment]
> 在 ResovleBatchInsert 函数中添加此 detemine 代码：
> 否则 if （列.CsharpType = 类型类型 （字节）） =
> 字符串十六进制 = 字符串。空;
> 用于 （int 索引 = 0; 索引 < （（字节+） 值）。长度;索引 =）
> = 十六进制 = 转换.Tostring（（（字节=）值）=索引=，16）。垫左（2，'0'）;
> •
> 缓冲区。附录（$"0x[十六进制]）;"0x=十六进制";
> }

ok
