### ISSUE TITLE
大神有空支持下数据库位运算符

### ISSUE THREAD

**Issue by heckledai** [1448376744/SqlBatis#3]
与运算 a & b , 
或运算 a | b , 
异或运算 a ^ b ,

**Comment by heckledai** [comment]
比如你有一个int字段作为状态
1：第一位表示下单成功
2：第二位表示是否支付
4：第三位表示是否发货
8：第四位表示是否收货
16：第五位表示是否评价
。。。
这样去更新状态的时候只要 
update 表
set status = a.status | 当前状态
where orderid = @orderid

不需要取出来加状态后再更新，这样并发不会出现不一致问题
位或操作也一样，这个算是计算机最基本的操作

**Comment by 1448376744** [comment]
> 比如你有一个int字段作为状态
> 1：第一位表示下单成功
> 2：第二位表示是否支付
> 4：第三位表示是否发货
> 8：第四位表示是否收货
> 16：第五位表示是否评价
> 。。。
> 这样去更新状态的时候只要
> update 表
> set status = a.status | 当前状态
> where orderid = @orderID
> 
> 不需要取出来加状态后再更新，这样并发不会出现不一致问题
> 位或操作也一样，这个算是计算机最基本的操作

SqlBatis支持这样的写法
比如Age是一个int类型的
DbContext.From<Student>()
.Set(a=>a.Age,a=>a.Age+1)
.Where(a=>a.Id==1)
.Update();

**Comment by 1448376744** [comment]
我已经加入了
