### ISSUE TITLE
BuildBatchInsertCommand 这个方法好像只有 MySql 实现了，能支持其它数据库实现吗

### ISSUE THREAD

**Issue by liqingwen2015** [1448376744/SqlBatis#5]

**Comment by 1448376744** [comment]
源码你也看到了，底层还是采用的字符串拼接。。。你可以直接写个字符串评价扩展上去。。。这意味着存在严重的注入风险，这种风险还是自己去承担吧。。。遗憾的是ado.net不支持批处理的api，听说正在制定，估计还需要挺长时间的。。。
